### ISSUE TITLE
Options to docker-compose.yml

### ISSUE THREAD

**Issue by VlaK0r** [swingmx/swingmusic#202]
Hello!
Thank you for your hard work!

Please tell me how to add these settings to docker-compose.yml?

![image](https://github.com/swing-opensource/swingmusic/assets/77666575/af5f99b7-2dd0-4980-a8af-ceaa1a6d0af9)

**Comment by VlaK0r** [comment]
I made changes, I started it, there are no errors.

**Comment by cwilvx** [comment]
Hi @VlaK0r 

Looks like this issue was resolved. I'll be closing it now.

If you still have the same issue, please leave a comment.

Thank you.
