### ISSUE TITLE
Question about the home page

### ISSUE THREAD

**Issue by VlaK0r** [swingmx/swingmusic#203]
Hello!
Thank you for your hard work!

Please tell me, is this how it should be or is there something wrong with my settings?

![image](https://github.com/swing-opensource/swingmusic/assets/77666575/72a543d3-2b16-4461-a311-6bf6a7eec1e5)

**Comment by cwilvx** [comment]
Hi @VlaK0r 

The `Browse Library` should be there. You should scroll to reveal something like this:

![image](https://github.com/swing-opensource/swingmusic/assets/48554537/2f142261-06b8-4373-9458-a8a017859d94)

**Comment by VlaK0r** [comment]
> The `Browse Library` section should be there. You should scroll to reveal something like this:

:)
I mean, it would be great if you didn't have to turn the mouse wheel.

**Comment by cwilvx** [comment]
@VlaK0r 

That's depends on your screen size ... plus later in future more items are coming to that page so scrolling is inevitable.

**Comment by VlaK0r** [comment]
> plus later in future

And where can I read about this future?
How do you plan to develop your project?

**Comment by cwilvx** [comment]
Hi @VlaK0r 

I haven't documented the future anywhere for now. But you can join us on [Telegram](https://t.me/+9n61PFcgKhozZDE0) if you'd like to know what's going on or maybe chat with the devs. You can [dm me](https://t.me/cwilvx) if you have specific questions.

Thanks.

**Comment by cwilvx** [comment]
Closing this as resolved.
