### ISSUE TITLE
Information and cover transmitted to the system.

### ISSUE THREAD

**Issue by VlaK0r** [swingmx/swingmusic#205]
Hello!
Thank you for your hard work!

![image](https://github.com/swing-opensource/swingmusic/assets/77666575/5921d0bc-76c4-4d14-ad42-e6cb9cc17da7)

The Linux system Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-18-amd64 (64-bit)
Graphics Platform: X11

In the system tray, when automatically switching tracks, track information and cover art are not displayed.
When the track is switched manually, everything is normal.

![image](https://github.com/swing-opensource/swingmusic/assets/77666575/4edbfe61-aef8-41dc-aa07-7ff1f87e7dfe)

At the same time, there is no problem in the browser.

![image](https://github.com/swing-opensource/swingmusic/assets/77666575/09d17fc6-1f56-412c-af7a-a663cd89d0c4)

**Comment by cwilvx** [comment]
Hi @VlaK0r 

Sorry for the late reply.

Is this issue happening with any other web page? Try with Spotify, etc. I'm on Ubuntu 22.04 Gnome 42.9 and everything works fine on my end.

Thank you.

**Comment by VlaK0r** [comment]
Hi @cwilvx.
I forgot about that already) I added a browser plugin for the integration of kde plasma and the problem was solved.
