### ISSUE TITLE
Web server binded to 127.0.0.1 instead of 0.0.0.0, which makes it not accessible from LAN

### ISSUE THREAD

**Issue by EricChan1989** [swingmx/swingmusic#228]
Dear Developer,

I tested with your latest windows build, and found that the related web server is not accessible from LAN despite I allowed port 1970 in Windows Firewall or even any ports and any protocols for this exe file.
I tried with netstat and see port 1970 is binded to 127.0.0.1, which is the root cause.
Could you please help to fix this？

Thanks a lot.

**Comment by cwilvx** [comment]
Hi @EricChan1989 

Thanks for using Swing Music. You can bind the server to "0.0.0.0" by using the `--host` flag when launching the server via the command line.

```bash
swingmusic --host 0.0.0.0 --port 1970
```

You can check out other flags in the [documentation](https://swingmx.com/guide/getting-started.html#options).

**Comment by EricChan1989** [comment]
thank you very much!!

**Comment by cwilvx** [comment]
Closing as resolved. Feel free to reopen if you still have the same issue.

@EricChan1989
