### ISSUE TITLE
The music stops when the song is finished if the screen is locked on Android

### ISSUE THREAD

**Issue by fperdigon** [swingmx/swingmusic#244]
The music stops when the song is finished if the screen is locked on Android.

I tried the installed web APP or in Chrome web browser.

I modified the battery usage profile and set it to unrestricted but no luck

I am using the 2.0 version beta 3 docker image

ghcr.io/swingmx/swingmusic:v2.0.0.beta8@sha256:9f67b0331e1a778b4c6c4b73b934a9e3918733cb542dd5e4e00ec260275dde3d

**Comment by fperdigon** [comment]
On Firefox for Android, the issue does not happen.  However the buttons to jump to previous or next song  with the screen locked are missing :(

**Comment by fperdigon** [comment]
On Edge for Android happens the same as with Chrome. They both have similar code basis so is expected I guess

**Comment by fperdigon** [comment]
I realize that the music stopping when the song is finished is a browser issue and not a SwingMusic app issue. However, I've added this issue because perhaps the behavior could be modified from within the app itself by applying some trick.

**Comment by cwilvx** [comment]
Hi @fperdigon 

This issue was patched by @Type-Delta (many thanks) in swingmx/webclient#38 and is available in the latest v2.0.0.beta10.

Check it out here: https://github.com/swingmx/swingmusic/releases/tag/v2.0.0.beta10
